name: Generate Alt Text

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  add-alt-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade openai markdown

      # 🔹 Debug secret availability
      - name: Debug OPENAI_API_KEY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ OPENAI_API_KEY is empty"
            exit 1
          else
            echo "✅ OPENAI_API_KEY loaded, last 4 chars: ${OPENAI_API_KEY: -4}"
          fi

      # 🔹 Run alt-text generator
      - name: Add alt text to markdown files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/add_alt_text.py

      # 🔹 Commit changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add generated alt text to markdown images" --no-gpg-sign || echo "No changes to commit"
          git push
